# Generated by Django 3.2.2 on 2021-05-30 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(verbose_name='Запущен на сайте?')),
                ('slug', models.SlugField(unique=True)),
                ('full_title', models.TextField(verbose_name='TITLE Название Страницы Сайта')),
                ('meta_description', models.TextField(verbose_name='МетаТег Описания')),
                ('meta_keywords', models.TextField(verbose_name='МетаТег Ключевые слова')),
                ('alt', models.TextField(verbose_name='Описание того, что изображено на картинке (название товара)')),
                ('title', models.CharField(max_length=255, verbose_name='Полное название продукта')),
                ('short_title', models.CharField(max_length=255, verbose_name='Краткое название, если основное очень длинное')),
                ('mini_image', models.ImageField(upload_to='product_photos/400x350', verbose_name='Изображение 400x350 для главной страницы')),
                ('image', models.ImageField(upload_to='product_photos/600x600', verbose_name='Изображение 600х600')),
                ('short_description', models.TextField(verbose_name='Краткое описание для главной страницы (до 100 символов)')),
                ('description', models.TextField(verbose_name='Описание товара подробноее не очень большое для начала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('active_substance', models.CharField(max_length=100, verbose_name='Действующее вещество')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('release_form', models.CharField(max_length=100, verbose_name='Форма выпуска')),
                ('packaging', models.CharField(max_length=100, verbose_name='Упаковка')),
                ('qty_in_a_package', models.CharField(max_length=100, verbose_name='Кол-во в упаковке')),
                ('full_description', models.TextField(verbose_name='Большой текст описания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
    ]
