# Generated by Django 3.2.2 on 2021-06-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_text', models.CharField(max_length=255, verbose_name='номер телефона')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(max_length=100, verbose_name='Код ATX'),
        ),
    ]
