# Generated by Django 3.2.2 on 2021-06-04 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210605_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.phone', verbose_name='Номер'),
        ),
    ]
