# Generated by Django 3.2.2 on 2021-06-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.phone', verbose_name='Номер'),
        ),
    ]
